# Site settings
title: DICE Cyfronet

# Build settings
markdown: kramdown

social:
  - title: github
    url: http://github.com/dice-cyfronet
  - title: youtube
    url: https://www.youtube.com/user/dicecyfronetpl
  - title: home
    url: http://dice.cyfronet.pl

projects:
  - name: PLGrid Core
    interval: 2014-2015
    pic: plgrid-core.png
    description: The main objective of the PLGrid Core project is further, significant extension of the PL-Grid Infrastructure computing resources, especially in ACC Cyfronet AGH, as a specialized competence centre in the field of distributed computing infrastructures, with particular emphasis on grid technologies, cloud computing and platforms supporting computations on big data.
  - name: PaaSage
    interval: 2012-2016
    pic: paasage.png
    description: PaaSage delivers an open and integrated platform to support model based lifecycle management of Cloud applications. The platform and the accompanying methodology allow model-based development, configuration, optimisation and deployment of existing and new applications, independently of the existing Cloud infrastructures.
  - name: Collage
    interval: 2011
    pic: collage.png
    description: The Collage Authoring Environment is a framework for collaborative preparation and publication of so-called executable papers. The environment enables researchers to seamlessly embed chunks of executable code (called snippets) into scientific publications, and to facilitate repeated execution of such snippets on underlying computing and data storage resources.
  - name: VPH-Share
    interval: 2011-2015
    pic: vph-share.jpg
    description: VPH-Share develops the organisational fabric and integrates optimized services to expose and share data and knowledge, jointly develop multiscale models for the composition of new VPH workflows, facilitate collaboration within the VPH community.
  - name: PLGrid Plus
    interval: 2011-2014
    pic: plgrid-plus.png
    description: PLGrid Plus project serves Polish scientific communities enabling extensive cooperation among them, as well as international cooperation in the scope of research activities in the area of ​​e-Science.
  - name: MAPPER
    interval: 2010-2013
    pic: mapper.png
    description: The MAPPER project responed to the critical need by developing computational strategies, software and services for distributed multiscale simulations across disciplines, exploiting existing and evolving European e-Infrastructure. This project was driven by the computational needs of seven exemplary multiscale problems from a variety of disciplines including Systems Biology, Fusion, Physiology, Engineering and nano-Material Science.
  - name: UrbanFlood
    interval: 2010-2012
    pic: urbanflood.png
    description: The mission of the UrbanFlood project was to investigate the use of sensors within flood embankments to support an online early warning system, real time emergency management and routine asset management. The Common Information Space (CIS), created in the scope of this project, provides a means for integration, over the Internet, of Early Warning Systems, sensors and application programs for public information and decision support.
  - name: PL-Grid
    interval: 2009-2012
    pic: plgrid.png
    description: The goal of the PL-Grid project was to provide the Polish scientific community with an IT supercomputing platform and a set of advanced tools to enable e-science research in various fields.
  - name: ViroLab
    interval: 2006-2009
    pic: virolab.png
    description: The ViroLab Project developed a virtual laboratory for research in the area of infectious diseases. In particular, it targeted the drug resistance problem in HIV (Human Immunodefficiency Virus) anti-viral therapy, using genetic information and computer modeling. GridSpace technology was used here as the main building block of the virtual laboratory, providing the core runtime, services and tools for programmers, computational scientists and virologists, enabling them to address important issues in modern treatment of infectious diseases through collaborative in-silico research.
  - name: GREDIA
    interval: 2006-2009
    pic: gredia.jpg
    description: The GREDIA Project prepared a system for access to multimedia data on the Grid, in the context of business applications. GREDIA focused on media and banking sectors. Here, GridSpace was applied as a core of the Appea platform, which enables users to quickly develop and deploy application scenarios, making use of the available Grid services and data resources.
  - name: CoreGRID
    interval: 2004-2008
    pic: coregrid.jpg
    description: The European Research Network on Foundations, Software Infrastructures and Applications for large scale distributed, GRID and Peer-to-Peer Technologies.
  - name: K-Wf Grid
    interval: 2004-2007
    pic: kwfgrid.png
    description: The Knowledge-based Workflow System for Grid Applications (K-Wf Grid) addressed the need for a better infrastructure for the future Grid environment.
  - name: CrossGrid
    interval: 2002-2005
    pic: crossgrid.png
    description: The CrossGrid project was oriented towards compute- and data-intensive applications that were characterized by the interaction with a person in a processing loop. Such applications required a response from the Grid to an action by a human agent in different time scales.

people:
  - name: Marian Bubak
    pic: mb
    position: Team leader
    social:
      - title: home
        url: http://www.cyf-kr.edu.pl/~gebubak/
  - name: Bartosz Baliś
    pic: bb
    position: Researcher
    social:
      - title: github
        url: https://github.com/balis
  - name: Tomasz Bartyński
    pic: tb
    position: Researcher, scientific developer
    social:
      - title: github
        url: https://github.com/djchrap
  - name: Tomasz Gubała
    pic: tg
    position: Researcher, programmer, entrepreneur
    social:
      - title: github
        url: https://github.com/Nuanda
  - name: Daniel Harężlak
    pic: dh
    position: Researcher, scientific developer
    social:
      - title: github
        url: https://github.com/dharezlak
  - name: Marek Kasztelnik
    pic: mk
    position: Researcher, scientific developer
    social:
      - title: twitter
        url: https://twitter.com/mkasztelnik
      - title: github
        url: https://github.com/mkasztelnik
      - title: stack-overflow
        url: http://stackoverflow.com/users/1535165/marek-kasztelnik
  - name: Maciej Malawski
    pic: mm
    position: Researcher
    social:
      - title: github
        url: https://github.com/malawski
  - name: Jan Meizner
    pic: jm
    position: System administrator
    social:
      # - title: github
      #   url: https://github.com/malawski
  - name: Piotr Nowakowski
    pic: pn
    position: Researcher, scientific developer
    social:
      - title: github
        url: https://github.com/nowakowski
  - name: Maciej Pawlik
    pic: mp
    position: Researcher, scientific developer
    social:
      - title: github
        url: https://github.com/mpawlik
  - name: Katarzyna Rycerz
    pic: kr
    position: Researcher
    social:
      - title: github
        url: https://github.com/kzajac
  - name: Paweł Suder
    pic: ps
    position: System administrator, scientific developer
    social:
      - title: github
        url: https://github.com/paoolo
      - title: twitter
        url: https://twitter.com/paoolo
  - name: Bartosz Wilk
    pic: bw
    position: Researcher, scientific developer
    social:
      - title: github
        url: https://github.com/bwilk